services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: keycloak
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://<HOST>:<PUERTO>/<NOMBRE_DB>
      KC_DB_USERNAME: <USUARIO_DB>
      KC_DB_PASSWORD: <CONTRASEÃ‘A_DB>
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: ["start-dev", "--hostname-strict=false"]
    ports:
      - "8080:8080"
